/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData chicken_leg = IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dinosaur = IconData(0xe99b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food_chain = IconData(0xe9d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knife_fork = IconData(0xea18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meat = IconData(0xea3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bug = IconData(0xf188, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drumstick_bite = IconData(0xf6d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skull_crossbones = IconData(0xf714, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bread_slice = IconData(0xf7ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
